services:
  adguardhome:
    image: adguard/adguardhome
    pull_policy: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - 53:53/tcp     # plain dns over tcp
      - 53:53/udp     # plain dns over udp
      - 3001:80/tcp   # http web interface
      - 3000:3000/tcp # initial setup web interface
    environment:
      TZ: America/Montreal
    volumes:
      - config:/opt/adguardhome/conf # app configuration
      - work:/opt/adguardhome/work   # app working directory

volumes:
  config:
    driver: local
  work:
    driver: local
